<template>
  <div class="question-container">
    <span class="question-text heading3">Koje ptice mogu upoznati?</span>
    <span class="question-text1 Content">
      You can take the quiz about birds in the database by accessing the
      &apos;Quiz&apos; route on our website. The quiz questions are generated by
      chat GPT and will test your knowledge about various bird species.
    </span>
  </div>
</template>

<script>
export default {
  name: 'Question',
  props: {
    Answer: {
      type: String,
      default:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non volutpat turpis. Mauris luctus rutrum mi ut rhoncus.',
    },
    Question: {
      type: String,
      default: 'What types of cars do you sell?',
    },
  },
}
</script>

<style scoped>
.question-container {
  gap: var(--dl-space-space-unit);
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  position: relative;
  align-items: flex-start;
  flex-direction: column;
}
.question-text {
  font-weight: 700;
  line-height: 1.6;
}
.question-text1 {
  color: var(--dl-color-gray-800);
  max-width: initial;
}
</style>
